version: 1.0

stages:
- init
- docker

steps:
  init:
    stage: init
    image: alpine
    commands:
    - cf_export IMAGE_NAME=${IMAGE_NAME:-oc/${{CF_REPO_NAME}}}
    - |
      if [[ ${{CF_BRANCH}} == "main" ]]; then
        cf_export TAG=latest
      else
        cf_export TAG=${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
      fi

  clone:
    stage: init
    type: git-clone
    git: oc-infra-bot
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_BRANCH}}

  build:
    stage: docker
    type: build
    working_directory: ${{clone}}/traffic_pod_autoscaler
    image_name: ${{IMAGE_NAME}}
    tag: ${{TAG}}
    no_cache: true
    no_cf_cache: true

  push:
    stage: docker
    type: push
    arguments:
      candidate: ${{build}}
      tag: ${{TAG}}
      image_name: ${{IMAGE_NAME}}
